Hw5
podlizzie/java-course-2023-tink pull request #7
Opened 2023-11-08 10:20 UTC by podlizzie

2023-11-09 15:14 UTC, kkkoltunov requested changes
отлично! поправь плиз минорные замечания и зачтем работу

2023-11-09 15:14 UTC, kkkoltunov commented on src/main/java/edu/hw5/Task1.java
> +        if (input.length == 0) {
кажется эта проверка все же должна быть в начале метода, а потом уже остальной код

2023-11-09 15:14 UTC, kkkoltunov commented on src/main/java/edu/hw5/Task2.java
> +    private static final int DAY13 = 13;
стоит отделять нижними подчеркиваниями сущености в названии констант 
```
private static final int DAY_13 = 13;
```

2023-11-09 15:15 UTC, kkkoltunov commented
за комменты отдельный плюс

2023-11-10 12:16 UTC, kkkoltunov commented
все ок, можно мерджить (а лучше дай мне коллаборатора чтобы я это тоже мог делать)

2023-11-10 15:24 UTC, podlizzie commented
> все ок, можно мерджить (а лучше дай мне коллаборатора чтобы я это тоже мог делать)

https://github.com/podlizzie/java-course-2023-tink/invitations

2023-11-10 15:36 UTC, merged